apiVersion: apps/v1
kind: Deployment
metadata:
  name: jovin-ui
  labels:
    app: jovin-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jovin-ui
  template:
    metadata:
      labels:
        app: jovin-ui
    spec:
      containers:
        - name: jovin-ui
          image: hexad3/virtualmenus:jovinui
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
